[package]
name = "rust-rag"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
futures = "0.3.31"
ollama-rs = { version = "0.2.6", features = ["stream"] }
qdrant-client = "1.13.0"
serde_json = "1.0.140"
